server:
  port: 8100
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /
    username: admin
    password: admin
    host: 127.0.0.1
  redis:
    host: 47.99.171.90
    password: 941008
    port: 6379
    database: 4
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        min-idle: 0
        max-idle: 10
    timeout: 1000
ly:
  sms:
    accessKeyId: LTAIOZd6njQ1pBZS # 你自己的accessKeyId
    accessKeySecret: jvTUSzOwVcXNDs95i38QzwXk4IaONK # 你自己的AccessKeySecret
    signName: 北极星的夜晚 # 签名名称
    verifyCodeTemplate: SMS_154587962 # 模板名称