server:
  port: 8000
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
    fetch-registry: false
    register-with-eureka: false