server:
  port: 8087
spring:
  application:
    name: auth-service
  redis:
    host: 47.99.171.90
    password: 941008
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        min-idle: 0
        max-idle: 10
    timeout: 1000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
ly:
  jwt:
    secret: ly@Login(Auth}*^31)&yun6%f3q2 # 登录校验的密钥
    pubKeyPath: E:\key\rsa\rsa.pub # 公钥地址
    priKeyPath: E:\key\rsa\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LY_TOKEN
    cookieMaxAge: 1800