server:
  port: 8088
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.99.171.90:3306/leyou?serverTimezone=GMT%2B8"useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 47.99.171.90
    password: 941008
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        min-idle: 0
        max-idle: 10
    timeout: 1000
  rabbitmq:
    username: admin
    password: admin
    virtual-host: /
    host: 127.0.0.1
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 30000ms
        multiplier: 2
      exchange: ly.item.exchange
    publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8000/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: /Users/bystander/id_rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    connectTimeoutMs: 5000
    readTimeoutMs: 10000
    notifyUrl: http://h7rmfa.natappfree.cc/wxpay/notify

